databases:
  - name: string_calculator
    databaseName: stringCalculator_development
    user: ror
    plan: free

services:
  - type: web
    plan: free
    name: stringCalculator_development
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stringCalculator_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
